rename	Gn.usfm	01_GEN_VG.usfm
rename	Ex.usfm	02_EXO_VG.usfm
rename	Lv.usfm	03_LEV_VG.usfm
rename	Nm.usfm	04_NUM_VG.usfm
rename	Dt.usfm	05_DEU_VG.usfm
rename	Jos.usfm	06_JOS_VG.usfm
rename	Jdc.usfm	07_JDG_VG.usfm
rename	Rt.usfm	08_RUT_VG.usfm
rename	1Rg.usfm	09_1SA_VG.usfm
rename	2Rg.usfm	10_2SA_VG.usfm
rename	3Rg.usfm	11_1KI_VG.usfm
rename	4Rg.usfm	12_2KI_VG.usfm
rename	1Par.usfm	13_1CH_VG.usfm
rename	2Par.usfm	14_2CH_VG.usfm
rename	Esr.usfm	15_EZR_VG.usfm
rename	Neh.usfm	16_NEH_VG.usfm
rename	Est.usfm	17_EST_VG.usfm
rename	Job.usfm	18_JOB_VG.usfm
rename	Ps.usfm	19_PSA_VG.usfm
rename	Pr.usfm	20_PRO_VG.usfm
rename	Ecl.usfm	21_ECC_VG.usfm
rename	Ct.usfm	22_SNG_VG.usfm
rename	Is.usfm	23_ISA_VG.usfm
rename	Jr.usfm	24_JER_VG.usfm
rename	Lam.usfm	25_LAM_VG.usfm
rename	Ez.usfm	26_EZK_VG.usfm
rename	Dn.usfm	27_DAN_VG.usfm
rename	Os.usfm	28_HOS_VG.usfm
rename	Joel.usfm	29_JOL_VG.usfm
rename	Am.usfm	30_AMO_VG.usfm
rename	Abd.usfm	31_OBA_VG.usfm
rename	Jon.usfm	32_JON_VG.usfm
rename	Mch.usfm	33_MIC_VG.usfm
rename	Nah.usfm	34_NAM_VG.usfm
rename	Hab.usfm	35_HAB_VG.usfm
rename	Soph.usfm	36_ZEP_VG.usfm
rename	Agg.usfm	37_HAG_VG.usfm
rename	Zach.usfm	38_ZEC_VG.usfm
rename	Mal.usfm	39_MAL_VG.usfm
rename	Mt.usfm	41_MAT_VG.usfm
rename	Mc.usfm	42_MRK_VG.usfm
rename	Lc.usfm	43_LUK_VG.usfm
rename	Jo.usfm	44_JHN_VG.usfm
rename	Act.usfm	45_ACT_VG.usfm
rename	Rom.usfm	46_ROM_VG.usfm
rename	1Cor.usfm	47_1CO_VG.usfm
rename	2Cor.usfm	48_2CO_VG.usfm
rename	Gal.usfm	49_GAL_VG.usfm
rename	Eph.usfm	50_EPH_VG.usfm
rename	Phlp.usfm	51_PHP_VG.usfm
rename	Col.usfm	52_COL_VG.usfm
rename	1Thes.usfm	53_1TH_VG.usfm
rename	2Thes.usfm	54_2TH_VG.usfm
rename	1Tim.usfm	55_1TI_VG.usfm
rename	2Tim.usfm	56_2TI_VG.usfm
rename	Tit.usfm	57_TIT_VG.usfm
rename	Phlm.usfm	58_PHM_VG.usfm
rename	Hbr.usfm	59_HEB_VG.usfm
rename	Jac.usfm	60_JAS_VG.usfm
rename	1Ptr.usfm	61_1PE_VG.usfm
rename	2Ptr.usfm	62_2PE_VG.usfm
rename	1Jo.usfm	63_1JN_VG.usfm
rename	2Jo.usfm	64_2JN_VG.usfm
rename	3Jo.usfm	65_3JN_VG.usfm
rename	Jud.usfm	66_JUD_VG.usfm
rename	Apc.usfm	67_REV_VG.usfm
rename	Tob.usfm	68_TOB_VG.usfm
rename	Jdt.usfm	69_JDT_VG.usfm
rename	Sap.usfm	71_WIS_VG.usfm
rename	Sir.usfm	72_SIR_VG.usfm
rename	Bar.usfm	73_BAR_VG.usfm
rename	1Mcc.usfm	78_1MA_VG.usfm
rename	2Mcc.usfm	79_2MA_VG.usfm
